//
//  LKConstants.h
//  GoogleTranslator
//

#define kLKLanguageArabic @"ar"
#define kLKLanguageBulgarian @"bg"
#define kLKLanguageCatalan @"ca"
#define kLKLanguageChinese @"zh"
#define kLKLanguageChineseSimplified @"zh-CN"
#define kLKLanguageChineseTraditional @"zh-TW"
#define kLKLanguageCroation @"cr"
#define kLKLanguageCzech @"cs"
#define kLKLanguageDanish @"da"
#define kLKLanguageDutch @"nl"
#define kLKLanguageEnglish @"en"
#define kLKLanguageFilipino @"tl"
#define kLKLanguageFinnish @"fi"
#define kLKLanguageFrench @"fr"
#define kLKLanguageGerman @"de"
#define kLKLanguageGreek @"el"
#define kLKLanguageHebrew @"iw"
#define kLKLanguageHindi @"hi"
#define kLKLanguageHungarian @"hu"
#define kLKLanguageIndonesian @"id"
#define kLKLanguageItalian @"it"
#define kLKLanguageJapanese @"ja"
#define kLKLanguageKorean @"ko"
#define kLKLanguageLatvian @"lv"
#define kLKLanguageLithuanian @"lt"
#define kLKLanguageNorwegian @"no"
#define kLKLanguagePolish @"pl"
#define kLKLanguagePortuguese @"pt"
#define kLKLanguageRomanian @"ro"
#define kLKLanguageRussian @"ru"
#define kLKLanguageSerbian @"sr"
#define kLKLanguageSlovak @"sk"
#define kLKLanguageSlovenian @"sl"
#define kLKLanguageSpanish @"es"
#define kLKLanguageSwedish @"sv"
#define kLKLanguageUkrainian @"uk"
#define kLKLanguageVietnamese @"vi"
