//
//  LKConstants.h
//  GoogleTranslator
//

#define LKLanguageARABIC @"ar"
#define LKLanguageBULGARIAN @"bg"
#define LKLanguageCATALAN @"ca"
#define LKLanguageCHINESE @"zh"
#define LKLanguageCHINESE_SIMPLIFIED @"zh-CN"
#define LKLanguageCHINESE_TRADITIONAL @"zh-TW"
#define LKLanguageCROATIAN @"cr"
#define LKLanguageCzech @"cs"
#define LKLanguageDANISH @"da"
#define LKLanguageDutch @"nl"
#define LKLanguageEnglish @"en"
#define LKLanguageFILIPINO @"tl"
#define LKLanguageFINNISH @"fi"
#define LKLanguageFrench @"fr"
#define LKLanguageGerman @"de"
#define LKLanguageGREEK @"el"
#define LKLanguageHEBREW @"iw"
#define LKLanguageHINDI @"hi"
#define LKLanguageINDONESIAN @"id"
#define LKLanguageITALIAN @"it"
#define LKLanguageJAPANESE @"ja"
#define LKLanguageKOREAN @"ko"
#define LKLanguageLATVIAN @"lv"
#define LKLanguageLITHUANIAN @"lt"
#define LKLanguageNORWEGIAN @"no"
#define LKLanguagePolish @"pl"
#define LKLanguagePortuguese @"pt"
#define LKLanguageROMANIAN @"ro"
#define LKLanguageRUSSIAN @"ru"
#define LKLanguageSERBIAN @"sr"
#define LKLanguageSlovak @"sk"
#define LKLanguageSlovenian @"sl"
#define LKLanguageSpanish @"es"
#define LKLanguageSWEDISH @"sv"
#define LKLanguageUKRANIAN @"uk"
#define LKLanguageVIETNAMESE @"vi"
